Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2527
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2578
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4233
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 23710
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2638
Not Found: /api-mobile
"GET /api-mobile HTTP/1.1" 404 2686
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\utilisateur_view.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2638
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2689
"GET /admin/ HTTP/1.1" 200 23710
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /admin/myapi/utilisateur/ HTTP/1.1" 200 19431
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/myapi/utilisateur/add/ HTTP/1.1" 200 42567
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/myapi/utilisateur/add/ HTTP/1.1" 302 0
"GET /admin/myapi/utilisateur/ HTTP/1.1" 200 19958
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/myapi/utilisateur/12/change/ HTTP/1.1" 200 43055
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /admin/myapi/utilisateur/ HTTP/1.1" 200 19725
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
Watching for file changes with StatReloader
"GET /admin/myapi/utilisateur/12/change/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/myapi/utilisateur/12/change/ HTTP/1.1" 200 4289
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2692
"POST /admin/login/?next=/admin/myapi/utilisateur/12/change/ HTTP/1.1" 302 0
"GET /admin/myapi/utilisateur/12/change/ HTTP/1.1" 200 43055
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"POST /admin/myapi/utilisateur/12/change/ HTTP/1.1" 302 0
"GET /admin/myapi/utilisateur/ HTTP/1.1" 200 19961
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/myapi/utilisateur/12/change/ HTTP/1.1" 200 43031
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"POST /admin/myapi/utilisateur/12/change/ HTTP/1.1" 302 0
"GET /admin/myapi/utilisateur/ HTTP/1.1" 200 19961
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
Not Found: /utilisateur/connexion
"POST /utilisateur/connexion HTTP/1.1" 404 2723
Internal Server Error: /api-mobile/utilisateur/connexion
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.33:8000/api-mobile/utilisateur/connexion/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /api-mobile/utilisateur/connexion HTTP/1.1" 500 69534
Internal Server Error: /api-mobile/utilisateur/connexion/
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\app_python\rdue\backend\mobiles_api\views_classes\utilisateur_view.py", line 23, in connexion
    response = ResponseClass(result=True, has_data=True, message="Connexion réussie", data=serializer.data)
                                                                                           ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `prenoms` is not valid for model `Utilisateur`.
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 500 142328
E:\applications\app_python\rdue\backend\mobiles_api\serializers.py changed, reloading.
Watching for file changes with StatReloader
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
Watching for file changes with StatReloader
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 90
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 135
Watching for file changes with StatReloader
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
Watching for file changes with StatReloader
Method Not Allowed: /api-mobile/utilisateur/connexion/
"GET /api-mobile/utilisateur/connexion/ HTTP/1.1" 405 49
Method Not Allowed: /api-mobile/utilisateur/connexion/
"GET /api-mobile/utilisateur/connexion/ HTTP/1.1" 405 49
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 90
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 252
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2638
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2689
"GET /admin/ HTTP/1.1" 200 23664
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
E:\applications\app_python\rdue\backend\mobiles_api\admin.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 24379
"GET /admin/mobiles_api/technicien/ HTTP/1.1" 200 17780
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /admin/mobiles_api/technicien/add/ HTTP/1.1" 200 21848
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
"GET /static/admin/css/forms.css HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/css/widgets.css HTTP/1.1" 304 0
"GET /static/admin/js/change_form.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/myapi/cooperative/ HTTP/1.1" 200 20658
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /admin/myapi/cooperative/12/change/ HTTP/1.1" 200 29119
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /admin/mobiles_api/technicien/ HTTP/1.1" 200 17780
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /admin/mobiles_api/technicien/add/ HTTP/1.1" 200 21848
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"POST /admin/mobiles_api/technicien/add/ HTTP/1.1" 302 0
"GET /admin/mobiles_api/technicien/ HTTP/1.1" 200 19384
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /admin/myapi/countrie/ HTTP/1.1" 200 19281
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
E:\applications\app_python\rdue\backend\mobiles_api\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/mobiles_api/technicien/ HTTP/1.1" 200 19122
"GET /admin/jsi18n/ HTTP/1.1" 200 8985
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /api/api-mobile/cooperative/get_cooperative
"GET /api/api-mobile/cooperative/get_cooperative?tel=0706623025 HTTP/1.1" 404 12462
Not Found: /api/cooperative/get_cooperative
"GET /api/cooperative/get_cooperative?tel=0706623025 HTTP/1.1" 404 12429
"GET /api-mobile/cooperative/get_cooperative?tel=0706623025 HTTP/1.1" 301 0
"GET /api-mobile/cooperative/get_cooperative/?tel=0706623025 HTTP/1.1" 200 104
"GET /api-mobile/cooperative/get_cooperative?tel=0767623025 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/cooperative/get_cooperative/
Traceback (most recent call last):
  File "E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py", line 22, in get_cooperative
    response = ResponseClass(result=True, has_data=True, message=f"Coopérative {technicien.cooperative.nomCoop}", data=serializer.data)
                                                                                                                       ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 1027, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class CooperativeSerializer missing "Meta" attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py", line 26, in get_cooperative
    return response.json_response()
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
"GET /api-mobile/cooperative/get_cooperative/?tel=0767623025 HTTP/1.1" 500 126921
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/cooperative/get_cooperative?tel=0767623025 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/cooperative/get_cooperative/
Traceback (most recent call last):
  File "E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py", line 22, in get_cooperative
    response = ResponseClass(result=True, has_data=True, message=f'Coopérative {technicien.cooperative.nomCoop}', data=serializer.data)
                                                                                                                       ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 1027, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class CooperativeSerializer missing "Meta" attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py", line 26, in get_cooperative
    return response.json_response()
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
"GET /api-mobile/cooperative/get_cooperative/?tel=0767623025 HTTP/1.1" 500 126921
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/cooperative/get_cooperative?tel=0767623025 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/cooperative/get_cooperative/
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py", line 22, in get_cooperative
    response = ResponseClass(result=True, has_data=True, message=f'Coopérative {technicien.cooperative.nomCoop}', data=serializer.data)
                                                                                                                       ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\serializers.py", line 1027, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class CooperativeSerializer missing "Meta" attribute
"GET /api-mobile/cooperative/get_cooperative/?tel=0767623025 HTTP/1.1" 500 122023
E:\applications\app_python\rdue\backend\mobiles_api\serializers.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/cooperative/get_cooperative?tel=0767623025 HTTP/1.1" 301 0
"GET /api-mobile/cooperative/get_cooperative/?tel=0767623025 HTTP/1.1" 200 400
"POST /api-mobile/utilisateur/connexion/ HTTP/1.1" 200 262
E:\applications\app_python\rdue\backend\mobiles_api\serializers.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/section/all_section_by_cooperative/
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 500 80649
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\section_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\section_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/section/all_section_by_cooperative/
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 500 80649
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\section_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/section/all_section_by_cooperative/
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 500 80649
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
Internal Server Error: /api-mobile/section/all_section_by_cooperative/
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 500 80649
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\section_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\section_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 200 3849
E:\applications\app_python\rdue\backend\mobiles_api\serializers.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 200 119
E:\applications\app_python\rdue\backend\mobiles_api\serializers.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/section/all_section_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
"GET /api-mobile/section/all_section_by_cooperative/?id_cooperative=10 HTTP/1.1" 200 3355
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\serializers.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\section_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\settings\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\producteur_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\planting_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\parcelle_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\detailplanting_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\campagne_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\parcelle_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\parcelle_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\parcelle_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\planting_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\planting_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\producteur_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\producteur_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\detailplanting_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/producteur/get_all_producteur_by_cooperative HTTP/1.1" 301 0
"GET /api-mobile/producteur/get_all_producteur_by_cooperative/ HTTP/1.1" 200 107
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\planting_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\detailplanting_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/campagne/get_all_active_campagne HTTP/1.1" 301 0
"GET /api-mobile/campagne/get_all_active_campagne/ HTTP/1.1" 200 1471
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\cooperative_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/cooperative/get_cooperative?technicien_tel=0767623025 HTTP/1.1" 301 0
"GET /api-mobile/cooperative/get_cooperative/?technicien_tel=0767623025 HTTP/1.1" 200 400
"GET /api-mobile/producteur/get_all_producteur_by_cooperative?id_cooperative=10 HTTP/1.1" 301 0
"GET /api-mobile/producteur/get_all_producteur_by_cooperative/?id_cooperative=10 HTTP/1.1" 200 476632
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\parcelle_view.py changed, reloading.
Watching for file changes with StatReloader
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\parcelle_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/parcelle/get_all_parcelle_by_producteur?code_producteur=052-A027 HTTP/1.1" 301 0
"GET /api-mobile/parcelle/get_all_parcelle_by_producteur/?code_producteur=052-A027 HTTP/1.1" 200 446
E:\applications\app_python\rdue\backend\mobiles_api\views_classes\planting_view.py changed, reloading.
Watching for file changes with StatReloader
"GET /api-mobile/planting/get_planting_by_parcelle?code_parcelle=052-A027-1 HTTP/1.1" 301 0
"GET /api-mobile/planting/get_planting_by_parcelle/?code_parcelle=052-A027-1 HTTP/1.1" 200 106
"GET /api-mobile/parcelle/get_all_parcelle_by_producteur?code_producteur=052-A015 HTTP/1.1" 301 0
"GET /api-mobile/parcelle/get_all_parcelle_by_producteur/?code_producteur=052-A015 HTTP/1.1" 200 450
"GET /api-mobile/planting/get_planting_by_parcelle?code_parcelle=052-A015-1 HTTP/1.1" 301 0
"GET /api-mobile/planting/get_planting_by_parcelle/?code_parcelle=052-A015-1 HTTP/1.1" 200 106
